/**
 * TypedGRPCWSClient - Type-safe wrapper for GRPCWSClient.
 *
 * This wrapper provides compile-time type safety for protobuf messages.
 * Use with types generated by any TypeScript protoc plugin:
 * - @bufbuild/protobuf
 * - protobuf-ts
 * - ts-proto
 * - etc.
 */

import { GRPCWSClient } from './grpcws-client';
import { ClientOptions, VoidHandler, ErrorHandler } from './types';

/**
 * Type-safe gRPC-WebSocket client with generic input/output types.
 *
 * This wrapper enforces type safety at compile time by parameterizing
 * the send and receive message types. Use with your protobuf-generated
 * TypeScript types.
 *
 * @typeParam TIn - The type of messages sent to the server
 * @typeParam TOut - The type of messages received from the server
 *
 * @example With @bufbuild/protobuf types
 * ```typescript
 * import { PlayerAction, GameState } from './gen/game_pb';
 *
 * const client = new TypedGRPCWSClient<PlayerAction, GameState>();
 * client.onMessage = (state: GameState) => {
 *   console.log('Players:', state.players);
 * };
 * await client.connect('ws://localhost:8080/ws/v1/sync');
 * client.send({ actionId: '1', move: { x: 10, y: 20 } });
 * ```
 *
 * @example With ts-proto types
 * ```typescript
 * import { GameCommand, CommandSummary } from './gen/game';
 *
 * const client = new TypedGRPCWSClient<GameCommand, CommandSummary>();
 * client.onMessage = (summary: CommandSummary) => {
 *   console.log(`Executed ${summary.commandsExecuted} commands`);
 * };
 * await client.connect('ws://localhost:8080/ws/v1/commands');
 * client.send({ commandId: '1', commandType: 'move' });
 * client.endSend();
 * ```
 */
export class TypedGRPCWSClient<TIn, TOut> {
  private client: GRPCWSClient;

  /** Called when a typed message is received */
  public onMessage: (data: TOut) => void = () => {};

  /** Called when the stream ends normally */
  public onStreamEnd: VoidHandler = () => {};

  /** Called when the server sends an error */
  public onError: ErrorHandler = () => {};

  /** Called when the connection closes */
  public onClose: VoidHandler = () => {};

  /** Called when a ping is received */
  public onPing: (pingId: number) => void = () => {};

  constructor(options: ClientOptions = {}) {
    this.client = new GRPCWSClient(options);
    this.setupHandlers();
  }

  /**
   * Connect to a grpcws WebSocket server.
   * @param url The WebSocket URL to connect to
   * @returns Promise that resolves when connected
   */
  connect(url: string): Promise<void> {
    return this.client.connect(url);
  }

  /**
   * Send a typed message to the server.
   * @param data The typed data payload to send
   */
  send(data: TIn): void {
    this.client.send(data);
  }

  /**
   * Signal that the client is done sending (half-close).
   */
  endSend(): void {
    this.client.endSend();
  }

  /**
   * Cancel the stream.
   */
  cancel(): void {
    this.client.cancel();
  }

  /**
   * Close the WebSocket connection.
   */
  close(): void {
    this.client.close();
  }

  /**
   * Check if the client is connected.
   */
  get isConnected(): boolean {
    return this.client.isConnected;
  }

  /**
   * Get the WebSocket ready state.
   */
  get readyState(): number {
    return this.client.readyState;
  }

  /**
   * Set up handlers to forward events with proper typing.
   */
  private setupHandlers(): void {
    this.client.onMessage = (data: unknown) => {
      // Cast to TOut - the protobuf JSON matches the TypeScript type
      this.onMessage(data as TOut);
    };

    this.client.onStreamEnd = () => {
      this.onStreamEnd();
    };

    this.client.onError = (error: string) => {
      this.onError(error);
    };

    this.client.onClose = () => {
      this.onClose();
    };

    this.client.onPing = (pingId: number) => {
      this.onPing(pingId);
    };
  }
}
